---
# setup pkg
- name: 開始調用各個部屬腳本
  include_tasks: run_setup.yml
  loop: "{{ group_names }}"
  when: 
    - item|regex_search('(^setup*)')
      #    - ansible_distribution == 'CentOS'
      #    - ansible_distribution_major_version == '7'
